### ISSUE TITLE
OSC 8 (Hyperlinks) Pass Through

### ISSUE THREAD

**Issue by enricozb** [eraserhd/kak-ansi#16]
OSC 8 outputs are passed through to kakoune, which kakoune can't render unfortunately. Not sure if this is a bug or not, but it would be nice if kak-ansi stripped these (and the hyperlink) out. For example when doing `man fish-doc`:
```
Some of the special features of fish are:

       • Extensive UI: ]8;;#color\Syntax highlighting]8;;\, ]8;;#autosuggestions\Autosuggestions]8;;\, ]8;;#tab-completion\tab completion]8;;\ and selection lists that can be navigated and
         filtered.
```
<img width="537" alt="image" src="https://github.com/user-attachments/assets/fa5cf9ea-6ede-4baa-a0d4-26b91f9317f0">

**Comment by krobelus** [comment]
I wonder how did you get `man fish-doc` to emit OSC 8? Did you use `script(1)`?

**Comment by enricozb** [comment]
@krobelus 

Does your `man fish-doc` not emit OSC 8? I built fish from commmit `a979b6341d7fc4c466b3992f25da3209e0808aaa` then did
```
cd build/user_doc/man
MANPATH=(pwd) command man fish-doc
```

**Comment by krobelus** [comment]
ok that works but I'm not sure how you make it so that the escape sequences show up in kakoune (where stdout is no TTY).
Either of `man fish-doc` or `!man fish-doc<ret>` shows up without escapes.

**Comment by enricozb** [comment]
@krobelus 

Again after building fish `a979b6341d7fc4c466b3992f25da3209e0808aaa` and doing
```
cd build/user_doc/man
MANPATH=(pwd) kak 'man fish-doc'
```
I get those escape sequences. I am using a custom `man-impl` command so perhaps that is related:
```kak
# changes how ansi escape sequences are stripped
# 1. always uses sed
# 2. see: https://superuser.com/a/380778
# 3. this won't work on macOS's sed
define-command -override -hidden -params ..3 man-impl %{ evaluate-commands %sh{
  buffer_name="$1"
  if [ -z "${buffer_name}" ]; then
    exit
  fi
  shift
  manout=$(mktemp "${TMPDIR:-/tmp}"/kak-man.XXXXXX)
  manerr=$(mktemp "${TMPDIR:-/tmp}"/kak-man.XXXXXX)
  colout=$(mktemp "${TMPDIR:-/tmp}"/kak-man.XXXXXX)
  env MANWIDTH=$(($kak_window_width - 10)) man "$@" > "$manout" 2> "$manerr"
  retval=$?

  sed -e 's/\x1b\[[0-9;]*m//g' > ${colout} < ${manout}

  rm ${manout}

  if [ "${retval}" -eq 0 ]; then
    printf %s\\n "
      edit -scratch %{*$buffer_name ${*}*}
      execute-keys '%|cat<space>${colout}<ret>gk'
      nop %sh{ rm ${colout}; rm ${manerr} }
      set-option buffer filetype man
      set-option window manpage $buffer_name $*
    "
  else
    printf '
      fail %%{%s}
      nop %%sh{ rm "%s"; rm "%s" }
    ' "$(cat "$manerr")" "${colout}" "${manerr}"
  fi
} }
```

**Comment by enricozb** [comment]
Sorry I think I'm losing it... I'm not even running `kak-ansi`.
