### ISSUE TITLE
Processing large files

### ISSUE THREAD

**Issue by JJK96** [eraserhd/kak-ansi#2]
When I do 

```
PAGER=kak git log
```
In the kakoune git repository, there is no highlighting even though the escape sequences have been deleted.
When I scroll to the bottom of the buffer, the ansi sequences are still there.
Running `ansi-render` manually removes the ansi sequences, but still no coloring.

It works fine for smaller git histories though.

**Comment by eraserhd** [comment]
Thanks for the report.   Not sure when I'll get to looking at this, it might be a few weeks.

**Comment by JJK96** [comment]
I tested with the `c` branch, now at least the top of the buffer is processed correctly. 
When I scroll to the bottom of the buffer the ansi sequences are still there, but running `ansi-render` manually colors it correctly.
This is probably because the rendering happens before the buffer is completely filled. I don't think we want to adapt that.

**Comment by eraserhd** [comment]
Hmm, I guess NormalIdle isn't handled if no user interaction occurs?  I wonder what events we get for a fifo.
