### ISSUE TITLE
Issue with using as Nixos Kakoune plugin

### ISSUE THREAD

**Issue by bhougland18** [eraserhd/kak-ansi#3]
Hello,

I looked at your Nixos dotfiles, as well as nix packages for plugins available to use with Kakoune, and it seems like the code below should work.  However, when I run "nixos-rebuild switch" it tells me that kak-ansi is an undefined variable.  The kak-buffers plugin that I also listed works as expected.  

Also, I am having trouble understanding what this plugin does by the description.  I having been looking for a command-line tool that will take my kakoune syntax highlighting from the editor and turn it into ansi color escaping when I send the text to a repl.  Is that what this plugin does?  It looks like from the code that it does that for a selection (which would be perfect).

Sorry to keep asking you questions.  It is tough to find people that share an overlapping interest in Nixos, Clojure, and Kakoune.

```
  {
    nixpkgs.overlays = [
      (self: super: {
        kakoune = super.wrapKakoune self.kakoune-unwrapped {
          configure = {
            plugins = with self.kakounePlugins; [
              parinfer-rust
              kak-ansi
              kak-buffers
            ];
          };
        };
      })
  ];

  environment.systemPackages = [ pkgs.kakoune ];
}
```

**Comment by eraserhd** [comment]
`kak-ansi` is available on the nixpkgs `master` branch.  I'm not sure if I did it long enough ago for it to be on a release.  If not, you'll need to add it in an overlay.

This plugin does not export Kakoune's highlighting -- it imports ANSI highlighting.  The `:ansi-render` command removes escape codes from a buffer and adds highlighting information.  It's useful for commands like `:make` which capture output to a fifo buffer.

I'll make a small note in the README.
